Create 16_how-do-i-change-the-privacy-settings-on-writings
fetlife/help pull request #102
Opened 2020-12-08 11:22 UTC by DarklingMuse

New FAQ topic from review in FAQ document

2020-12-14 20:39 UTC, sylee- requested changes
I didn't mean to star a review.  I meant to add a comment and now I can't figure out how to get rid of the review.  :(

2020-12-14 20:39 UTC, sylee- commented on 03_pictures-videos-and-writings/16_how-do-i-change-the-privacy-settings-on-writings
> +You can change this before you post your Writing by selecting the ‘Friends-Only’ option from the drop down menu at the bottom of the new Writing box.
"drop-down" instead of "drop down"

2020-12-17 10:34 UTC, DarklingMuse commented
I've edited this to remove mentions of drop down menus / too many specifics so that it is still relevant if things move around / it's concise... I think it still makes sense? 😅

2021-03-03 11:06 UTC, DarklingMuse commented
replaced by https://github.com/fetlife/help/pull/126

2021-03-03 11:06 UTC, closed without merging