Update 12_how-do-i-change-my-email-address.md
fetlife/help pull request #89
Opened 2020-11-05 20:59 UTC by sylee-

2020-11-05 21:04 UTC, EGypsy commented
👍

2020-11-05 21:06 UTC, emfet commented
Looks good to me :)

2020-11-06 18:26 UTC, Haribishop approved these changes

2020-11-16 13:36 UTC, nielsenramon commented on 02_profiles/12_how-do-i-change-my-email-address.md
> +2. Select “Update Settings" in the dropdown menu.
First quote is different here. We need to standardize on `"` I think.

2020-11-16 13:37 UTC, nielsenramon commented on 02_profiles/12_how-do-i-change-my-email-address.md
> +3. Click "Update" next to your email address under the Account tab. Your current email address is already filled in.
`...next to your current email address...`

I would remove `Your current email address is already filled in.`

2020-11-16 13:37 UTC, nielsenramon commented on 02_profiles/12_how-do-i-change-my-email-address.md
> +4. Input your new email address plus your current password.
Input your new email address **and** your current password.

2020-11-16 13:39 UTC, nielsenramon commented on 02_profiles/12_how-do-i-change-my-email-address.md
>  So you want all your FetLife email to be going to a particular email address that is different than the one you signed up on, huh? No worries!
Let's remove this part. Feels condescending!

2020-11-16 13:41 UTC, nielsenramon commented on 02_profiles/12_how-do-i-change-my-email-address.md
> +1. Click on the hamburger menu (the icon with three horizontal lines) at the top right-hand corner of the page.
`Open the FetLife Main Navigation Menu`

And FetLife Navigation Menu links to a new help document where we explain what this is and where to find it.

2020-11-16 13:42 UTC, nielsenramon commented on 02_profiles/12_how-do-i-change-my-email-address.md
> +5. Click on the red “Update Email” button.
If we ever change this color, we will need to change it everywhere again :D

I would just state: `Submit the form`

2020-11-16 13:43 UTC, nielsenramon requested changes
I reviewed this one very in detail so I can go over it with @johnbaku hopefully today!

2020-11-16 19:20 UTC, nielsenramon approved these changes

2020-11-16 19:21 UTC, nielsenramon commented
@fetlife/caretakers John and I reviewed and wrote this one ourselves to give you a better understanding of how we would like FAQ articles to look like in the future. Mind going over this in detail and propose other new ones 1 by 1 to me please? 🙏 

Thanks!

2020-11-16 19:21 UTC, merged

2020-11-17 11:38 UTC, BobbyGH commented
Reviewed. 

I'd add one more line to each FAQ entry, something like: 

Should you still need assistance with this or something else, please drop us a line at support@fetlife.com

At least for the time being...

2020-11-17 12:00 UTC, nielsenramon commented
@BobbyGH Let's not do that please. I don't see the point in driving more work to caretakers right now!